name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      custom_message:
        type: string
        required: true
        description: Enter a custom message
      run_job:
        description: Run Specific Job
        type: boolean
        required: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Printing Custom Message
      run: echo "${{inputs.custom_message}}"
      